TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB_INSTALLS += $(TOP)/hyrel3dSup/devhyrel3d.db
DB_INSTALLS += $(TOP)/hyrel3dSup/devhyrel3d.proto

#=======================================
include $(TOP)/configure/RULES
